@startuml Object Diagram

package "Object Diagram - Clientes Gestor" {

Customer -right- Address
Customer -left- Phone

object Customer {
  id : 1
  name: "Fulano da Silva"
  email: "eu@meuemail.com"
  cpf : "111.111.111-11"
  birthdate: "01/01/2000"
  sex: "Masculino"
  maritalstatus: "Solteiro"
}

object Address {
  id : 1
  address_category : "Residencial"
  type : "Rua"
  name : "Principal"
  number : "01"
  district : "Centro"
  city : "Minha Cidade"
  state : "SP"
  zip_code : "11.111-111"
  complement : "Casa de esquina"
}

object Phone {
  id : 1
  phone : "(11) 9 1111-1111"
  type : "Residencial"
}

}

@enduml