@startuml Class Diagram

package "Class Diagram - Clientes Gestor" {

ClientesController -left- ClientesView
ClientesController -right- Clientes
ClientesController -- AddressController
ClientesController -- TelefonesController

AddressController -left- AddressView
AddressController -- Address

TelefonesController -right- TelefonesView
TelefonesController -- Telefones

class ClientesController {
    -model: Clientes
    -view: ClientesView
    +list()
    +new()
    +save()
    +remove()
    +update()
}

class Clientes {
    -id : Int
    -saudacao: String
    -nome: String
    -email: String
    -cpf : String
    -data_de_nascimento: Date
    -sexo_cliente: String
    -estado_civil_cliente: String
    +clientes_list()
    +clientes_delete()
    +clientes_new()
    +clientes_update()
}

class AddressController {
    -model: Address
    -view: AddressView
    +list()
    +new()
    +save()
    +remove()
}

class TelefonesController {
    -model: Address
    -view: TelefonesView
    +novo()
    +cadastrar()
    +apagar()
}

class Address {
    -id : Int
    -cpf : String
    -address_category : String
    -type : String
    -name : String
    -number : String
    -district : String
    -city : String
    -state : String
    -zip_code : String
    -complement : String
    +post_address_list()
    +post_address_delete()
    +post_address_new()
}

class Telefones {
    -id : Int
    -cpf : String
    -tipo : String
    -telefone : String
    +telefone_list()
    +telefone_delete()
    +telefone_insert()
}

class AddressView {
}

@enduml