@startuml Object Diagram

package "Object Diagram - Clientes Gestor" {

Clientes -right- Address
Clientes -left- Telefone

object Clientes {
  id : 1
  saudacao: "Sr."
  nome: "Fulano da Silva"
  email: "eu@meuemail.com"
  cpf : "111.111.111-11"
  data_de_nascimento: "01/01/2000"
  sexo_cliente: "Masculino"
  estado_civil_cliente: "Solteiro"
}

object Address {
  id : 1
  cpf : "111.111.111-11"
  address_category : "Residencial"
  type : "Rua"
  name : "Principal"
  number : "01"
  district : "Centro"
  city : "Minha Cidade"
  state : "SP"
  zip_code : "11.111-111"
  complement : "Casa de esquina"
}

object Telefone {
  id : 1
  cpf : "111.111.111-11"
  phone : "(11) 9 1111-1111"
  type : "Residencial"
}

}

@enduml